basic:
  image_tag_version: "latest"
  controller_image_name: "ghcr.io/spotify/volcano/vc-controller-manager"
  scheduler_image_name: "ghcr.io/spotify/volcano/vc-scheduler"
  admission_image_name: "ghcr.io/spotify/volcano/vc-webhook-manager"
  admission_secret_name: "volcano-admission-secret"
  scheduler_config_file: "config/volcano-scheduler.conf"
  image_pull_secret: ""
  admission_port: 8443
  crd_version: "v1beta1"
custom:
  metrics_enable: "false"
