name: release
on:
  push:
    tags: ["v*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/${{ github.repository }}
    steps:
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=image_tag::${GITHUB_REF/refs\/tags\//}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.1.tar.gz
          tar -xf musl-1.2.1.tar.gz && cd musl-1.2.1
          ./configure
          make && sudo make install

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ./src/github.com/${{ github.repository }}

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run verify test
        run: |
          make verify
          make TAG=latest generate-yaml
          make verify-generated-yaml
          make unit-test
        working-directory: ./src/github.com/${{ github.repository }}

      - name: Login to Github container registry
        uses: docker/login-action@v1.1.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Images
        run: make release-images
        env:
          IMAGE_PREFIX: ghcr.io/spotify/volcano/vc
          IMAGE_TAG: ${{ steps.prep.outputs.image_tag }}
          CC: /usr/local/musl/bin/musl-gcc
        working-directory: ./src/github.com/${{ github.repository }}
